version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      spring-boot:
        patterns:
          - "org.springframework.boot*"
      aws-sdk:
        patterns:
          - "software.amazon.awssdk*"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
