-- ============================================================
-- V18: Track per-user coupon usage to enforce usage_limit_per_user
-- and first_time_only, which existed on the Coupon domain model
-- (Coupon.canBeUsedByUser) but had no persistence to enforce them.
-- ============================================================

CREATE TABLE coupon_usages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id BIGINT NOT NULL REFERENCES coupons(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    order_id BIGINT NULL REFERENCES orders(id),
    discount_amount DECIMAL(10, 2) NOT NULL,
    used_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL,
    created_by VARCHAR(255) NULL,
    updated_by VARCHAR(255) NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_coupon_usage_coupon_user ON coupon_usages(coupon_id, user_id);
CREATE INDEX idx_coupon_usage_user_id ON coupon_usages(user_id);
CREATE INDEX idx_coupon_usage_order_id ON coupon_usages(order_id);
