package com.eshop.app.seller.api.response;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Response DTO representing the seller dashboard metrics snapshot.
 * Aggregates store overview statistics, sales metrics, order lifecycle counters,
 * top performing products, and recent order entries.
 *
 * @since 1.0
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@JsonInclude(JsonInclude.Include.NON_NULL)
@Schema(description = "Seller dashboard metrics and overview information")
public class SellerDashboardResponse implements Serializable {

    private static final long serialVersionUID = 1L;

    /** Store overview information. */
    @Schema(description = "Overview information for the seller store")
    private StoreOverview storeOverview;

    /** Sales metrics summaries. */
    @Schema(description = "Sales performance metrics and aggregations")
    private SalesMetrics salesMetrics;

    /** Order management totals. */
    @Schema(description = "Order fulfillment counts by status")
    private OrderManagement orderManagement;

    /** Top performing products list. */
    @Schema(description = "List of top-selling products by quantity and revenue")
    private List<TopProductResponse> topProducts;

    /** Recent orders placed. */
    @Schema(description = "List of recent orders placed in the seller store")
    private List<RecentOrderResponse> recentOrders;

    /** Authenticated user role identifier. */
    @Schema(description = "Associated user dashboard role", example = "SELLER")
    private String role;

    /** Snapshot creation timestamp. */
    @Schema(description = "ISO-8601 formatted UTC snapshot timestamp", example = "2026-07-04T05:00:00Z")
    @JsonFormat(shape = JsonFormat.Shape.STRING)
    private Instant timestamp;

    /**
     * Inner class representing the store overview details.
     */
    @Getter
    @Setter
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @Schema(description = "Store overview statistics")
    public static class StoreOverview implements Serializable {
        private static final long serialVersionUID = 1L;

        @Schema(description = "Name of the seller store", example = "Farmer's Organic Store")
        private String storeName;

        @Schema(description = "Current active status of the store", example = "ACTIVE")
        private String storeStatus;

        @Schema(description = "Total number of products in the catalog", example = "150")
        private Long totalProducts;

        @Schema(description = "Number of active visible products", example = "120")
        private Long activeProducts;

        @Schema(description = "Number of products currently out of stock", example = "5")
        private Long outOfStockProducts;

        @Schema(description = "Average rating of the store (0.0 to 5.0)", example = "4.8")
        private Double storeRating;
    }

    /**
     * Inner class representing sales metrics.
     */
    @Getter
    @Setter
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @Schema(description = "Sales performance metrics")
    public static class SalesMetrics implements Serializable {
        private static final long serialVersionUID = 1L;

        @Schema(description = "Total revenue generated today, inclusive of standard discounts.", example = "1250.50")
        private BigDecimal todaySales;

        @Schema(description = "Total revenue generated in the last 7 days.", example = "8400.00")
        private BigDecimal weeklySales;

        @Schema(description = "Total revenue generated in the current calendar month.", example = "35000.00")
        private BigDecimal monthlySales;

        @Schema(description = "Lifetime total revenue generated by the store.", example = "150000.00")
        private BigDecimal totalSales;
    }

    /**
     * Inner class representing order counters.
     */
    @Getter
    @Setter
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @Schema(description = "Order lifecycle count indicators")
    public static class OrderManagement implements Serializable {
        private static final long serialVersionUID = 1L;

        @Schema(description = "Total new orders requiring confirmation", example = "3")
        private Long newOrders;

        @Schema(description = "Total orders currently in processing or packing", example = "8")
        private Long processingOrders;

        @Schema(description = "Total orders shipped and in-transit", example = "12")
        private Long shippedOrders;

        @Schema(description = "Total successfully completed orders", example = "240")
        private Long completedOrders;
    }
}
